# in _config.yml
title: "TTS for ASR"
author: "<a href='https://cdminix.me'>Christoph Minixhofer</a> <a href='https://twitter.com/cdminix'><img height='24' width='24' src='_images/twitter.svg' alt='Twitter' style='width:24px'></a>"
copyright: "2021"
logo: figures/unicorn.png

execute:
  execute_notebooks: "auto"

repository:
  url                       : "https://github.com/cdminix/tts-for-asr"  # Online location of your book
  path_to_book              : .  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

html:
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://cdminix.me/tts-for-asr
  favicon: images/favicon.ico
  use_fullscreen_button: false
  comments:
    hypothesis: false
  extra_footer: "Licensed under CC-BY 4.0 Template based on <a href='goodresearch.dev'>goodresearch.dev</a>]."

launch_buttons:
  thebe             : true
  notebook_interface: classic

thebe_config:
  repository_url : "https://github.com/cdminix/tts-for-asr"  # Online location of your book
  path_to_book   : "docs/"  # Optional path to your book, relative to the repository root
  branch         : main  # Which branch of the repository should be used when creating links (optional)

parse:
  myst_enable_extensions:
    - colon_fence
    - substitution
    - dollarmath
    - deflist
    - html_image

sphinx:
  extra_extensions:
  - sphinxext.opengraph
  config:
    ogp_site_url: "cdminix.me/tts-for-asr"
    ogp_image: "https://goodresearch.dev/_images/unicorn.png"
    ogp_description_length: 200